// Code generated by "stringer -type role -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[roleUser-0]
	_ = x[roleAssistant-1]
}

const _role_name = "userassistant"

var _role_index = [...]uint8{0, 4, 13}

func (i role) String() string {
	if i >= role(len(_role_index)-1) {
		return "role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _role_name[_role_index[i]:_role_index[i+1]]
}
